### ISSUE TITLE
Error: cannot import name 'PartialMessageable' from 'discord.channel'

### ISSUE THREAD

**Issue by Jourdelune** [jnawk/Quart-Discord#15]
Hi, I have an error:
```py
Traceback (most recent call last):
  File "site.py", line 2, in <module>
    from quart_discord import DiscordOAuth2Session, requires_authorization, Unauthorized
  File "/home/jourdelune/.local/lib/python3.8/site-packages/quart_discord/__init__.py", line 4, in <module>
    from .client import DiscordOAuth2Session
  File "/home/jourdelune/.local/lib/python3.8/site-packages/quart_discord/client.py", line 3, in <module>
    import discord
  File "/home/jourdelune/.local/lib/python3.8/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/home/jourdelune/.local/lib/python3.8/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/home/jourdelune/.local/lib/python3.8/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/home/jourdelune/.local/lib/python3.8/site-packages/discord/webhook/async_.py", line 46, in <module>
    from ..channel import PartialMessageable
ImportError: cannot import name 'PartialMessageable' from 'discord.channel' (/home/jourdelune/.local/lib/python3.8/site-packages/discord/channel.py)
```

**Comment by Jourdelune** [comment]
Finnaly, after re install PyCord, that work
