### ISSUE TITLE
jwt.exceptions.DecodeError: Not enough segments

### ISSUE THREAD

**Issue by rereyy** [jnawk/Quart-Discord#17]
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 190, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/quart/app.py", line 1489, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/home/container/.local/lib/python3.8/site-packages/quart/app.py", line 1514, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/home/container/.local/lib/python3.8/site-packages/quart/app.py", line 964, in handle_user_exception
    raise error
  File "/home/container/.local/lib/python3.8/site-packages/quart/app.py", line 1512, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/container/.local/lib/python3.8/site-packages/quart/app.py", line 1557, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "./site/fdpy.py", line 59, in callback
    return await discord.callback()
  File "/home/container/.local/lib/python3.8/site-packages/quart_discord/client.py", line 163, in callback
    return jwt.decode(state, current_app.config["SECRET_KEY"], algorithms="HS256")
  File "/home/container/.local/lib/python3.8/site-packages/jwt/api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/home/container/.local/lib/python3.8/site-packages/jwt/api_jwt.py", line 90, in decode_complete
    decoded = api_jws.decode_complete(
  File "/home/container/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 149, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "/home/container/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 193, in _load
    raise DecodeError("Not enough segments") from err
    
  
![image](https://user-images.githubusercontent.com/67708477/143485340-c8200079-a4f4-4fbb-9494-e636f5810269.png)

**Comment by MaximumMaxxx** [comment]
Idk if you've solved this yet, but if you're still stuck or for anyone seeing this in the future. You have to set your callback in discord to the same as the address your connecting to. If you're using localhost:8000 your callback can't be 127.0.0.1:8000 or vice versa. 
Connect with 127.0.0.1:8000 or set your callback to localhost:8000

**Comment by jnawk** [comment]
almost certainly a configuration issue, given literally everyone who uses this library must call this method.  (it's working for my app)

**Comment by MiroslavRosenov** [comment]
Has anyone managed to fixed this? Its working fine on 127.0.0.1, but as soon as I put in online it breaks with this error

**Comment by MaximumMaxxx** [comment]
Make sure you have your online ip as a callback address in discord and have it set as your callback address in your app.

**Comment by MiroslavRosenov** [comment]
That was not the issue, somehow the site cookies were blocked

**Comment by jnawk** [comment]
> That was not the issue, somehow the site cookies were blocked

coookies are a function of domain, so an ip address and a domain name aren't the same, cookies for one won't be sent to the other.

**Comment by MiroslavRosenov** [comment]
That's not what I meant... the `create_session` function could not save `state` in the session

**Comment by jnawk** [comment]
what's the output of `pip freeze` ? specifically the version of the package providing `jwt`
